package cn.edu.nenu.acm.oj.entitybeans;

// Generated 2013-1-18 15:52:51 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contest generated by hbm2java
 */
@Entity
@Table(name = "contest", catalog = "nenuoj")
public class Contest implements java.io.Serializable {

	private Integer id;
	private Contest contest;
	private Message message;
	private User user;
	private String title;
	private Date startTime;
	private Date endTime;
	private Integer contestType;
	private Date lastUpdateTime;
	private Serializable remark;
	private Set<Solution> solutions = new HashSet<Solution>(0);
	private Set<User> users = new HashSet<User>(0);
	private Set<ProblemDescription> problemDescriptions = new HashSet<ProblemDescription>(
			0);
	private Set<Contest> contests = new HashSet<Contest>(0);

	public Contest() {
	}

	public Contest(User user, String title, Integer contestType,
			Date lastUpdateTime) {
		this.user = user;
		this.title = title;
		this.contestType = contestType;
		this.lastUpdateTime = lastUpdateTime;
	}

	public Contest(Contest contest, Message message, User user, String title,
			Date startTime, Date endTime, Integer contestType,
			Date lastUpdateTime, Serializable remark, Set<Solution> solutions,
			Set<User> users, Set<ProblemDescription> problemDescriptions,
			Set<Contest> contests) {
		this.contest = contest;
		this.message = message;
		this.user = user;
		this.title = title;
		this.startTime = startTime;
		this.endTime = endTime;
		this.contestType = contestType;
		this.lastUpdateTime = lastUpdateTime;
		this.remark = remark;
		this.solutions = solutions;
		this.users = users;
		this.problemDescriptions = problemDescriptions;
		this.contests = contests;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clone_id")
	public Contest getContest() {
		return this.contest;
	}

	public void setContest(Contest contest) {
		this.contest = contest;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "message_id")
	public Message getMessage() {
		return this.message;
	}

	public void setMessage(Message message) {
		this.message = message;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "host_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "title", nullable = false, length = 128)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_time", length = 19)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_time", length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "contest_type", nullable = false)
	public Integer getContestType() {
		return this.contestType;
	}

	public void setContestType(Integer contestType) {
		this.contestType = contestType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update_time", nullable = false, length = 19)
	public Date getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	@Column(name = "remark")
	public Serializable getRemark() {
		return this.remark;
	}

	public void setRemark(Serializable remark) {
		this.remark = remark;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contest")
	public Set<Solution> getSolutions() {
		return this.solutions;
	}

	public void setSolutions(Set<Solution> solutions) {
		this.solutions = solutions;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "contest_has_user", catalog = "nenuoj", joinColumns = { @JoinColumn(name = "contest_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "user_id", nullable = false, updatable = false) })
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "contest_has_problem_description", catalog = "nenuoj", joinColumns = { @JoinColumn(name = "contest_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "problem_description_id", nullable = false, updatable = false) })
	public Set<ProblemDescription> getProblemDescriptions() {
		return this.problemDescriptions;
	}

	public void setProblemDescriptions(
			Set<ProblemDescription> problemDescriptions) {
		this.problemDescriptions = problemDescriptions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contest")
	public Set<Contest> getContests() {
		return this.contests;
	}

	public void setContests(Set<Contest> contests) {
		this.contests = contests;
	}

}
