package cn.edu.nenu.acm.oj.entitybeans;

// Generated 2013-1-10 21:36:30 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LoginLog generated by hbm2java
 */
@Entity
@Table(name = "login_log", catalog = "nenuoj")
public class LoginLog implements java.io.Serializable {

	private Integer id;
	private User user;
	private Date loginTime;
	private Date logoutTime;
	private String ipaddr;
	private Serializable remark;

	public LoginLog() {
	}

	public LoginLog(User user, String ipaddr) {
		this.user = user;
		this.ipaddr = ipaddr;
	}

	public LoginLog(User user, Date loginTime, Date logoutTime, String ipaddr,
			Serializable remark) {
		this.user = user;
		this.loginTime = loginTime;
		this.logoutTime = logoutTime;
		this.ipaddr = ipaddr;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "login_time", length = 19)
	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "logout_time", length = 19)
	public Date getLogoutTime() {
		return this.logoutTime;
	}

	public void setLogoutTime(Date logoutTime) {
		this.logoutTime = logoutTime;
	}

	@Column(name = "ipaddr", nullable = false, length = 128)
	public String getIpaddr() {
		return this.ipaddr;
	}

	public void setIpaddr(String ipaddr) {
		this.ipaddr = ipaddr;
	}

	@Column(name = "remark")
	public Serializable getRemark() {
		return this.remark;
	}

	public void setRemark(Serializable remark) {
		this.remark = remark;
	}

}
