package cn.edu.nenu.acm.oj.entitybeans;

// Generated 2013-1-10 21:36:30 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SystemConfig generated by hbm2java
 */
@Entity
@Table(name = "system_config", catalog = "nenuoj")
public class SystemConfig implements java.io.Serializable {

	private Integer id;
	private String attribute;
	private Serializable value;
	private Date lastUpdateTime;

	public SystemConfig() {
	}

	public SystemConfig(String attribute, Date lastUpdateTime) {
		this.attribute = attribute;
		this.lastUpdateTime = lastUpdateTime;
	}

	public SystemConfig(String attribute, Serializable value,
			Date lastUpdateTime) {
		this.attribute = attribute;
		this.value = value;
		this.lastUpdateTime = lastUpdateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "attribute", nullable = false, length = 128)
	public String getAttribute() {
		return this.attribute;
	}

	public void setAttribute(String attribute) {
		this.attribute = attribute;
	}

	@Column(name = "value")
	public Serializable getValue() {
		return this.value;
	}

	public void setValue(Serializable value) {
		this.value = value;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update_time", nullable = false, length = 19)
	public Date getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

}
